modLoader     = "javafml"
loaderVersion = "${loader_version_range}"
license       = "${mod_license}"

[[mods]]
modId       = "baedoorlib"
version     = "${mod_version}"
displayName = "BaedoorLib"
authors     = "Toma400 - author, DylanVHS - textures"
description = '''
${mod_description}
'''

[[dependencies.baedoorlib]]
    modId        = "forge"
    mandatory    = true
    versionRange = "${forge_version_range}"
    ordering     = "NONE"
    side         = "BOTH"

[[dependencies.baedoorlib]]
    modId        = "minecraft"
    mandatory    = true
    versionRange = "${minecraft_version_range}"
    ordering     = "NONE"
    side         = "BOTH"